# Generated by Django 5.2.6 on 2025-10-10 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_post_id_employee_post_and_more'),
        ('movement_inventory', '0001_initial'),
        ('products', '0001_initial'),
        ('sales', '0002_salesdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementinventory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='movementinventory',
            name='movement_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Movimiento'),
        ),
        migrations.AlterField(
            model_name='movementinventory',
            name='movement_type',
            field=models.CharField(choices=[('ENT', 'Entrada (Compra/Ingreso)'), ('SAL', 'Salida (Venta/Daño)'), ('AJU', 'Ajuste de Inventario'), ('TRA', 'Transferencia entre Almacenes'), ('DEV', 'Devolución de Cliente')], default='AJU', max_length=50, verbose_name='Tipo de Movimiento'),
        ),
        migrations.AlterField(
            model_name='movementinventory',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='movementinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='movementinventory',
            name='quantity',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='movementinventory',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sales', verbose_name='Venta Relacionada'),
        ),
    ]
