# Generated by Django 5.2.6 on 2025-10-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement_inventory', '0003_alter_movementinventory_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementinventory',
            name='movement_type',
            field=models.CharField(choices=[('ENT', 'Entrada (Compra/Ingreso)'), ('SAL', 'Salida (Venta/Daño)'), ('AJU', 'Ajuste de Inventario'), ('TRA', 'Transferencia entre Almacenes'), ('DEV', 'Devolución de Cliente')], default='AJU', max_length=10, verbose_name='Tipo de Movimiento'),
        ),
    ]
