# Generated by Django X.X on YYYY-MM-DD (tu fecha)

from django.db import migrations, models # <--- ¡models agregado aquí!
from django.db.models import F # Importamos F para el manejo seguro de campos

def update_employee_states(apps, schema_editor):
    """
    Función para cambiar valores antiguos (ej. 'Activo', 'Inactivo') a los nuevos 
    códigos de 3 letras (ej. 'ACT', 'INA'). Esto debe ejecutarse ANTES de reducir el max_length.
    """
    Employee = apps.get_model('employee', 'Employee')
    
    # Mapeo de valores que superan 3 caracteres a sus códigos de 3 letras.
    mapping = {
        'Activo': 'ACT',
        'Inactivo': 'INA',
        'Vacaciones': 'VAC',
        'Licencia': 'LIC',
        'Suspendido': 'SUS',
        'Retirado': 'RET',
    }
    
    for old_value, new_code in mapping.items():
        # Usamos __startswith o __icontains para ser más flexibles con mayúsculas/minúsculas 
        # o espacios extra en los datos antiguos.
        Employee.objects.filter(state__icontains=old_value).update(state=new_code)
        
    # Limpieza de valores que puedan ser NULL o vacíos (asegurando el default)
    Employee.objects.filter(state__isnull=True).update(state='ACT')
    Employee.objects.filter(state__exact='').update(state='ACT')


class Migration(migrations.Migration):

    dependencies = [
        # Aseguramos que la dependencia apunte a la migración 0002 que acabamos de modificar
        ('employee', '0002_remove_employee_post_id_employee_post_and_more'),
    ]

    operations = [
        # 1. Ejecuta la función de Python para corregir los datos largos.
        migrations.RunPython(update_employee_states, migrations.RunPython.noop),
        
        # 2. AHORA es seguro aplicar la reducción de max_length a 3 caracteres, 
        # ya que la data de la columna 'state' ha sido limpiada.
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo'), ('VAC', 'Vacaciones'), ('LIC', 'Licencia'), ('SUS', 'Suspendido'), ('RET', 'Retirado')], default='ACT', max_length=50, verbose_name='Estado Laboral'),
        ),
    ]
