# Generated by Django 5.2.6 on 2025-10-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo'), ('VAC', 'Vacaciones'), ('LIC', 'Licencia'), ('SUS', 'Suspendido'), ('RET', 'Retirado')], default='ACT', max_length=50, verbose_name='Estado Laboral'),
        ),
    ]
