# Generated by Django 5.2.6 on 2025-10-10 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('employee', '0002_remove_employee_post_id_employee_post_and_more'),
        ('products', '0002_remove_product_state_product_product_state_and_more'),
        ('sales', '0002_salesdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='state',
        ),
        migrations.AddField(
            model_name='sales',
            name='sale_state',
            field=models.CharField(choices=[('CMP', 'Completada'), ('PEN', 'Pendiente de Pago'), ('CAN', 'Cancelada'), ('DEV', 'Devuelta'), ('PRC', 'En Proceso (Borrador)')], default='PEN', max_length=50, verbose_name='Estado de la Venta'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(choices=[('EFE', 'Efectivo'), ('TCR', 'Tarjeta de Crédito'), ('TDE', 'Tarjeta de Débito'), ('TRA', 'Transferencia Bancaria'), ('CHQ', 'Cheque'), ('PMO', 'Pago Móvil'), ('CRP', 'Criptomoneda')], default='EFE', max_length=50, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='quantity',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.sales', verbose_name='Venta'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario'),
        ),
    ]
