# Generated by Django 5.2.6 on 2025-10-10 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('employee', '0003_alter_employee_state'),
        ('products', '0003_alter_product_product_state'),
        ('sales', '0004_alter_sales_payment_method_alter_sales_sale_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto'),
        ),
    ]
