# Generated by Django 5.2.6 on 2025-10-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sales_customer_alter_sales_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(choices=[('EFE', 'Efectivo'), ('TCR', 'Tarjeta de Crédito'), ('TDE', 'Tarjeta de Débito'), ('TRA', 'Transferencia Bancaria'), ('CHQ', 'Cheque'), ('PMO', 'Pago Móvil'), ('CRP', 'Criptomoneda')], default='EFE', max_length=50, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_state',
            field=models.CharField(choices=[('CMP', 'Completada'), ('PEN', 'Pendiente de Pago'), ('CAN', 'Cancelada'), ('DEV', 'Devuelta'), ('PRC', 'En Proceso (Borrador)')], default='PEN', max_length=50, verbose_name='Estado de la Venta'),
        ),
    ]
