# Generated by Django 5.2.6 on 2025-10-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_state_product_product_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_state',
            field=models.CharField(choices=[('ACT', 'Activo (Disponible)'), ('INA', 'Inactivo (No disponible)'), ('AGO', 'Agotado (Sin stock)'), ('DSC', 'Descontinuado')], default='ACT', max_length=15, verbose_name='Estado del Producto'),
        ),
    ]
